modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/Ketheroth/vanillaextension/issues"
[[mods]]
modId="vanillaextension"
version="1.17.1-1.1.0"
displayName="Vanilla Extension"
updateJSONURL="https://ketheroth.com/mods/vanillaextension.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/vanilla-extension"
logoFile="logo.png"
authors="Ketheroth"
description='''
You can convert most of the vanilla blocks into stairs, slabs, fences, walls and trapdoors.
'''
[[dependencies.vanillaextension]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vanillaextension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
