modLoader="javafml"
loaderVersion="[31,)"
license="MIT License"
issueTrackerURL="https://github.com/nbrichau/vanillaextension/issues"
[[mods]]
modId="vanillaextension"
version="1.15.2-1.0.5"
displayName="Vanilla Extension"
#updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/vanilla-extension"
logoFile="logo.png"
credits="Thanks for downloading my mod"
authors="Nelson Brichau"
description='''
You can convert most of the vanilla blocks into stairs, slabs, fences and walls
'''
[[dependencies.vanillaextension]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vanillaextension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
