modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
issueTrackerURL="https://github.com/nbrichau/vanillaextension/issues"
[[mods]]
modId="vanillaextension"
version="1.16.5-1.0.17"
displayName="Vanilla Extension"
updateJSONURL="https://ketheroth.github.io/mods/uncrafter.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/vanilla-extension"
logoFile="logo.png"
credits="Thanks for downloading my mod"
authors="Nelson Brichau"
description='''
You can convert most of the vanilla blocks into stairs, slabs, fences, walls and trapdoors.
'''
[[dependencies.vanillaextension]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vanillaextension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
