package com.nbrichau.vanillaextension.init;

import com.nbrichau.vanillaextension.VanillaExtension;
import com.nbrichau.vanillaextension.slabs.*;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(VanillaExtension.MODID)
@Mod.EventBusSubscriber(modid = VanillaExtension.MODID, bus = Bus.MOD)
public class SlabInit {

	public static final Block farmland_slab = null;
	public static final Block grass_block_slab = null;
	public static final Block dirt_slab = null;
	public static final Block coarse_dirt_slab = null;
	public static final Block podzol_slab = null;
	public static final Block bedrock_slab = null;
	public static final Block sand_slab = null;
	public static final Block red_sand_slab = null;
	public static final Block gravel_slab = null;
	public static final Block gold_ore_slab = null;
	public static final Block iron_ore_slab = null;
	public static final Block coal_ore_slab = null;
	public static final Block nether_gold_ore_slab = null;
	public static final Block oak_log_slab = null;
	public static final Block spruce_log_slab = null;
	public static final Block birch_log_slab = null;
	public static final Block jungle_log_slab = null;
	public static final Block acacia_log_slab = null;
	public static final Block dark_oak_log_slab = null;
	public static final Block stripped_oak_log_slab = null;
	public static final Block stripped_spruce_log_slab = null;
	public static final Block stripped_birch_log_slab = null;
	public static final Block stripped_jungle_log_slab = null;
	public static final Block stripped_acacia_log_slab = null;
	public static final Block stripped_dark_oak_log_slab = null;
	public static final Block oak_wood_slab = null;
	public static final Block spruce_wood_slab = null;
	public static final Block birch_wood_slab = null;
	public static final Block jungle_wood_slab = null;
	public static final Block acacia_wood_slab = null;
	public static final Block dark_oak_wood_slab = null;
	public static final Block stripped_oak_wood_slab = null;
	public static final Block stripped_spruce_wood_slab = null;
	public static final Block stripped_birch_wood_slab = null;
	public static final Block stripped_jungle_wood_slab = null;
	public static final Block stripped_acacia_wood_slab = null;
	public static final Block stripped_dark_oak_wood_slab = null;
	public static final Block oak_leaves_slab = null;
	public static final Block spruce_leaves_slab = null;
	public static final Block birch_leaves_slab = null;
	public static final Block jungle_leaves_slab = null;
	public static final Block acacia_leaves_slab = null;
	public static final Block dark_oak_leaves_slab = null;
	public static final Block sponge_slab = null;
	public static final Block wet_sponge_slab = null;
	public static final Block glass_slab = null;
	public static final Block lapis_ore_slab = null;
	public static final Block lapis_block_slab = null;
	public static final Block chiseled_sandstone_slab = null;
	public static final Block white_wool_slab = null;
	public static final Block orange_wool_slab = null;
	public static final Block magenta_wool_slab = null;
	public static final Block light_blue_wool_slab = null;
	public static final Block yellow_wool_slab = null;
	public static final Block lime_wool_slab = null;
	public static final Block pink_wool_slab = null;
	public static final Block gray_wool_slab = null;
	public static final Block light_gray_wool_slab = null;
	public static final Block cyan_wool_slab = null;
	public static final Block purple_wool_slab = null;
	public static final Block blue_wool_slab = null;
	public static final Block brown_wool_slab = null;
	public static final Block green_wool_slab = null;
	public static final Block red_wool_slab = null;
	public static final Block black_wool_slab = null;
	public static final Block gold_block_slab = null;
	public static final Block iron_block_slab = null;
	public static final Block tnt_slab = null;
	public static final Block bookshelf_slab = null;
	public static final Block obsidian_slab = null;
	public static final Block spawner_slab = null;
	public static final Block diamond_ore_slab = null;
	public static final Block diamond_block_slab = null;
	public static final Block redstone_ore_slab = null;
	public static final Block ice_slab = null;
	public static final Block snow_block_slab = null;
	public static final Block clay_slab = null;
	public static final Block pumpkin_slab = null;
	public static final Block netherrack_slab = null;
	public static final Block soul_sand_slab = null;
	public static final Block soul_soil_slab = null;
	public static final Block glowstone_slab = null;
	public static final Block carved_pumpkin_slab = null;
	public static final Block jack_o_lantern_slab = null;
	public static final Block white_stained_glass_slab = null;
	public static final Block orange_stained_glass_slab = null;
	public static final Block magenta_stained_glass_slab = null;
	public static final Block light_blue_stained_glass_slab = null;
	public static final Block yellow_stained_glass_slab = null;
	public static final Block lime_stained_glass_slab = null;
	public static final Block pink_stained_glass_slab = null;
	public static final Block gray_stained_glass_slab = null;
	public static final Block light_gray_stained_glass_slab = null;
	public static final Block cyan_stained_glass_slab = null;
	public static final Block purple_stained_glass_slab = null;
	public static final Block blue_stained_glass_slab = null;
	public static final Block brown_stained_glass_slab = null;
	public static final Block green_stained_glass_slab = null;
	public static final Block red_stained_glass_slab = null;
	public static final Block black_stained_glass_slab = null;
	public static final Block oak_trapdoor_slab = null;
	public static final Block spruce_trapdoor_slab = null;
	public static final Block birch_trapdoor_slab = null;
	public static final Block jungle_trapdoor_slab = null;
	public static final Block acacia_trapdoor_slab = null;
	public static final Block dark_oak_trapdoor_slab = null;
	public static final Block cracked_stone_brick_slab = null;
	public static final Block chiseled_stone_brick_slab = null;
	public static final Block brown_mushroom_block_slab = null;
	public static final Block red_mushroom_block_slab = null;
	public static final Block mushroom_stem_slab = null;
	public static final Block iron_bars_slab = null;
	public static final Block melon_slab = null;
	public static final Block vine_slab = null;
	public static final Block mycelium_slab = null;
	public static final Block end_stone_slab = null;
	public static final Block dragon_egg_slab = null;
	public static final Block redstone_lamp_slab = null;
	public static final Block emerald_ore_slab = null;
	public static final Block emerald_block_slab = null;
	public static final Block redstone_block_slab = null;
	public static final Block nether_quartz_ore_slab = null;
	public static final Block hopper_slab = null;
	public static final Block chiseled_quartz_block_slab = null;
	public static final Block quartz_pillar_slab = null;
	public static final Block white_terracotta_slab = null;
	public static final Block orange_terracotta_slab = null;
	public static final Block magenta_terracotta_slab = null;
	public static final Block light_blue_terracotta_slab = null;
	public static final Block yellow_terracotta_slab = null;
	public static final Block lime_terracotta_slab = null;
	public static final Block pink_terracotta_slab = null;
	public static final Block gray_terracotta_slab = null;
	public static final Block light_gray_terracotta_slab = null;
	public static final Block cyan_terracotta_slab = null;
	public static final Block purple_terracotta_slab = null;
	public static final Block blue_terracotta_slab = null;
	public static final Block brown_terracotta_slab = null;
	public static final Block green_terracotta_slab = null;
	public static final Block red_terracotta_slab = null;
	public static final Block black_terracotta_slab = null;
	public static final Block slime_block_slab = null;
	public static final Block iron_trapdoor_slab = null;
	public static final Block sea_lantern_slab = null;
	public static final Block hay_block_slab = null;
	public static final Block terracotta_slab = null;
	public static final Block coal_block_slab = null;
	public static final Block packed_ice_slab = null;
	public static final Block chiseled_red_sandstone_slab = null;
	public static final Block purpur_pillar_slab = null;
	public static final Block grass_path_slab = null;
	public static final Block magma_block_slab = null;
	public static final Block nether_wart_block_slab = null;
	public static final Block bone_block_slab = null;
	public static final Block white_glazed_terracotta_slab = null;
	public static final Block orange_glazed_terracotta_slab = null;
	public static final Block magenta_glazed_terracotta_slab = null;
	public static final Block light_blue_glazed_terracotta_slab = null;
	public static final Block yellow_glazed_terracotta_slab = null;
	public static final Block lime_glazed_terracotta_slab = null;
	public static final Block pink_glazed_terracotta_slab = null;
	public static final Block gray_glazed_terracotta_slab = null;
	public static final Block light_gray_glazed_terracotta_slab = null;
	public static final Block cyan_glazed_terracotta_slab = null;
	public static final Block purple_glazed_terracotta_slab = null;
	public static final Block blue_glazed_terracotta_slab = null;
	public static final Block brown_glazed_terracotta_slab = null;
	public static final Block green_glazed_terracotta_slab = null;
	public static final Block red_glazed_terracotta_slab = null;
	public static final Block black_glazed_terracotta_slab = null;
	public static final Block white_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.WHITE_CONCRETE)).setRegistryName("white_concrete_slab");
	public static final Block orange_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.ORANGE_CONCRETE)).setRegistryName("orange_concrete_slab");
	public static final Block magenta_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.MAGENTA_CONCRETE)).setRegistryName("magenta_concrete_slab");
	public static final Block light_blue_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE)).setRegistryName("light_blue_concrete_slab");
	public static final Block yellow_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.YELLOW_CONCRETE)).setRegistryName("yellow_concrete_slab");
	public static final Block lime_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIME_CONCRETE)).setRegistryName("lime_concrete_slab");
	public static final Block pink_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.PINK_CONCRETE)).setRegistryName("pink_concrete_slab");
	public static final Block gray_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.GRAY_CONCRETE)).setRegistryName("gray_concrete_slab");
	public static final Block light_gray_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE)).setRegistryName("light_gray_concrete_slab");
	public static final Block cyan_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.CYAN_CONCRETE)).setRegistryName("cyan_concrete_slab");
	public static final Block purple_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.PURPLE_CONCRETE)).setRegistryName("purple_concrete_slab");
	public static final Block blue_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLUE_CONCRETE)).setRegistryName("blue_concrete_slab");
	public static final Block brown_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.BROWN_CONCRETE)).setRegistryName("brown_concrete_slab");
	public static final Block green_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.GREEN_CONCRETE)).setRegistryName("green_concrete_slab");
	public static final Block red_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.RED_CONCRETE)).setRegistryName("red_concrete_slab");
	public static final Block black_concrete_slab = new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLACK_CONCRETE)).setRegistryName("black_concrete_slab");
	public static final Block white_concrete_powder_slab = null;
	public static final Block orange_concrete_powder_slab = null;
	public static final Block magenta_concrete_powder_slab = null;
	public static final Block light_blue_concrete_powder_slab = null;
	public static final Block yellow_concrete_powder_slab = null;
	public static final Block lime_concrete_powder_slab = null;
	public static final Block pink_concrete_powder_slab = null;
	public static final Block gray_concrete_powder_slab = null;
	public static final Block light_gray_concrete_powder_slab = null;
	public static final Block cyan_concrete_powder_slab = null;
	public static final Block purple_concrete_powder_slab = null;
	public static final Block blue_concrete_powder_slab = null;
	public static final Block brown_concrete_powder_slab = null;
	public static final Block green_concrete_powder_slab = null;
	public static final Block red_concrete_powder_slab = null;
	public static final Block black_concrete_powder_slab = null;
	public static final Block dried_kelp_block_slab = null;
	public static final Block dead_tube_coral_block_slab = null;
	public static final Block dead_brain_coral_block_slab = null;
	public static final Block dead_bubble_coral_block_slab = null;
	public static final Block dead_fire_coral_block_slab = null;
	public static final Block dead_horn_coral_block_slab = null;
	public static final Block tube_coral_block_slab = null;
	public static final Block brain_coral_block_slab = null;
	public static final Block bubble_coral_block_slab = null;
	public static final Block fire_coral_block_slab = null;
	public static final Block horn_coral_block_slab = null;
	public static final Block blue_ice_slab = null;
	public static final Block honey_block_slab = null;
	public static final Block honeycomb_block_slab = null;
	public static final Block warped_stem_slab = null;
	public static final Block stripped_warped_stem_slab = null;
	public static final Block warped_hyphae_slab = null;
	public static final Block stripped_warped_hyphae_slab = null;
	public static final Block warped_nylium_slab = null;
	public static final Block warped_wart_block_slab = null;
	public static final Block crimson_stem_slab = null;
	public static final Block stripped_crimson_stem_slab = null;
	public static final Block crimson_hyphae_slab = null;
	public static final Block stripped_crimson_hyphae_slab = null;
	public static final Block crimson_nylium_slab = null;
	public static final Block shroomlight_slab = null;
	public static final Block netherite_block_slab = null;
	public static final Block ancient_debris_slab = null;
	public static final Block crying_obsidian_slab = null;
	public static final Block basalt_slab = null;
	public static final Block polished_basalt_slab = null;
	public static final Block cracked_polished_blackstone_brick_slab = null;
	public static final Block chiseled_polished_blackstone_slab = null;
	public static final Block gilded_blackstone_slab = null;
	public static final Block chiseled_nether_brick_slab = null;
	public static final Block cracked_nether_brick_slab = null;
	public static final Block quartz_brick_slab = null;

	@SubscribeEvent
	public static void registerSlabBlock(final RegistryEvent.Register<Block> event) {
		event.getRegistry().register(new FarmlandSlab(AbstractBlock.Properties.copy(Blocks.FARMLAND)).setRegistryName("farmland_slab"));
		event.getRegistry().register(new GrassBlockSlab(AbstractBlock.Properties.copy(Blocks.GRASS_BLOCK)).setRegistryName("grass_block_slab"));
		event.getRegistry().register(new DirtSlab(AbstractBlock.Properties.copy(Blocks.DIRT)).setRegistryName("dirt_slab"));
		event.getRegistry().register(new CoarseDirtSlab(AbstractBlock.Properties.copy(Blocks.COARSE_DIRT)).setRegistryName("coarse_dirt_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PODZOL)).setRegistryName("podzol_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BEDROCK)).setRegistryName("bedrock_slab"));
		event.getRegistry().register(new FallingSlab(AbstractBlock.Properties.copy(Blocks.SAND)).setRegistryName("sand_slab"));
		event.getRegistry().register(new FallingSlab(AbstractBlock.Properties.copy(Blocks.RED_SAND)).setRegistryName("red_sand_slab"));
		event.getRegistry().register(new FallingSlab(AbstractBlock.Properties.copy(Blocks.GRAVEL)).setRegistryName("gravel_slab"));
		event.getRegistry().register(new OreSlab(AbstractBlock.Properties.copy(Blocks.GOLD_ORE)).setRegistryName("gold_ore_slab"));
		event.getRegistry().register(new OreSlab(AbstractBlock.Properties.copy(Blocks.IRON_ORE)).setRegistryName("iron_ore_slab"));
		event.getRegistry().register(new OreSlab(AbstractBlock.Properties.copy(Blocks.COAL_ORE)).setRegistryName("coal_ore_slab"));
		event.getRegistry().register(new OreSlab(AbstractBlock.Properties.copy(Blocks.NETHER_GOLD_ORE)).setRegistryName("nether_gold_ore_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.WOOD).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("oak_log_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.PODZOL).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("spruce_log_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SAND).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("birch_log_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.DIRT).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("jungle_log_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_ORANGE).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("acacia_log_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_BROWN).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("dark_oak_log_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.WOOD).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_oak_log_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.PODZOL).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_spruce_log_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SAND).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_birch_log_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.DIRT).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_jungle_log_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_ORANGE).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_acacia_log_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_BROWN).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_dark_oak_log_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.WOOD).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("oak_wood_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.PODZOL).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("spruce_wood_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SAND).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("birch_wood_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.DIRT).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("jungle_wood_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_GRAY).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("acacia_wood_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_BROWN).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("dark_oak_wood_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.WOOD).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_oak_wood_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.PODZOL).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_spruce_wood_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SAND).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_birch_wood_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.DIRT).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_jungle_wood_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_ORANGE).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_acacia_wood_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_BROWN).strength(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_dark_oak_wood_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.LEAVES).strength(0.2f).sound(SoundType.GRASS).noOcclusion().isViewBlocking((state, reader, pos) -> false)).setRegistryName("oak_leaves_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.LEAVES).strength(0.2f).sound(SoundType.GRASS).noOcclusion().isViewBlocking((state, reader, pos) -> false)).setRegistryName("spruce_leaves_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.LEAVES).strength(0.2f).sound(SoundType.GRASS).noOcclusion().isViewBlocking((state, reader, pos) -> false)).setRegistryName("birch_leaves_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.LEAVES).strength(0.2f).sound(SoundType.GRASS).noOcclusion().isViewBlocking((state, reader, pos) -> false)).setRegistryName("jungle_leaves_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.LEAVES).strength(0.2f).sound(SoundType.GRASS).noOcclusion().isViewBlocking((state, reader, pos) -> false)).setRegistryName("acacia_leaves_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.LEAVES).strength(0.2f).sound(SoundType.GRASS).noOcclusion().isViewBlocking((state, reader, pos) -> false)).setRegistryName("dark_oak_leaves_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.SPONGE)).setRegistryName("sponge_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.WET_SPONGE)).setRegistryName("wet_sponge_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GLASS)).setRegistryName("glass_slab"));
		event.getRegistry().register(new OreSlab(AbstractBlock.Properties.copy(Blocks.LAPIS_ORE)).setRegistryName("lapis_ore_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LAPIS_BLOCK)).setRegistryName("lapis_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CHISELED_SANDSTONE)).setRegistryName("chiseled_sandstone_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.WHITE_WOOL)).setRegistryName("white_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.ORANGE_WOOL)).setRegistryName("orange_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.MAGENTA_WOOL)).setRegistryName("magenta_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_BLUE_WOOL)).setRegistryName("light_blue_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.YELLOW_WOOL)).setRegistryName("yellow_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIME_WOOL)).setRegistryName("lime_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PINK_WOOL)).setRegistryName("pink_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GRAY_WOOL)).setRegistryName("gray_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_GRAY_WOOL)).setRegistryName("light_gray_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CYAN_WOOL)).setRegistryName("cyan_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PURPLE_WOOL)).setRegistryName("purple_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLUE_WOOL)).setRegistryName("blue_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BROWN_WOOL)).setRegistryName("brown_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GREEN_WOOL)).setRegistryName("green_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.RED_WOOL)).setRegistryName("red_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLACK_WOOL)).setRegistryName("black_wool_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GOLD_BLOCK)).setRegistryName("gold_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.IRON_BLOCK)).setRegistryName("iron_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.TNT)).setRegistryName("tnt_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BOOKSHELF)).setRegistryName("bookshelf_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.OBSIDIAN)).setRegistryName("obsidian_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.SPAWNER)).setRegistryName("spawner_slab"));
		event.getRegistry().register(new OreSlab(AbstractBlock.Properties.copy(Blocks.DIAMOND_ORE)).setRegistryName("diamond_ore_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DIAMOND_BLOCK)).setRegistryName("diamond_block_slab"));
		event.getRegistry().register(new RedstoneOreSlab(AbstractBlock.Properties.copy(Blocks.REDSTONE_ORE)).setRegistryName("redstone_ore_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.ICE).friction(0.98F).strength(0.5F).sound(SoundType.GLASS).noOcclusion()).setRegistryName("ice_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.SNOW_BLOCK)).setRegistryName("snow_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CLAY)).setRegistryName("clay_slab"));
		event.getRegistry().register(new PumpkinSlab(AbstractBlock.Properties.copy(Blocks.PUMPKIN)).setRegistryName("pumpkin_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.NETHERRACK)).setRegistryName("netherrack_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.SAND, MaterialColor.COLOR_BROWN).strength(0.5F).speedFactor(0.4F).sound(SoundType.SAND)).setRegistryName("soul_sand_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.SOUL_SOIL)).setRegistryName("soul_soil_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GLOWSTONE)).setRegistryName("glowstone_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CARVED_PUMPKIN)).setRegistryName("carved_pumpkin_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.JACK_O_LANTERN)).setRegistryName("jack_o_lantern_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.WHITE_STAINED_GLASS)).setRegistryName("white_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.ORANGE_STAINED_GLASS)).setRegistryName("orange_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.MAGENTA_STAINED_GLASS)).setRegistryName("magenta_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_BLUE_STAINED_GLASS)).setRegistryName("light_blue_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.YELLOW_STAINED_GLASS)).setRegistryName("yellow_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIME_STAINED_GLASS)).setRegistryName("lime_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PINK_STAINED_GLASS)).setRegistryName("pink_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GRAY_STAINED_GLASS)).setRegistryName("gray_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_GRAY_STAINED_GLASS)).setRegistryName("light_gray_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CYAN_STAINED_GLASS)).setRegistryName("cyan_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PURPLE_STAINED_GLASS)).setRegistryName("purple_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLUE_STAINED_GLASS)).setRegistryName("blue_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BROWN_STAINED_GLASS)).setRegistryName("brown_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GREEN_STAINED_GLASS)).setRegistryName("green_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.RED_STAINED_GLASS)).setRegistryName("red_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLACK_STAINED_GLASS)).setRegistryName("black_stained_glass_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.OAK_TRAPDOOR)).setRegistryName("oak_trapdoor_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.SPRUCE_TRAPDOOR)).setRegistryName("spruce_trapdoor_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BIRCH_TRAPDOOR)).setRegistryName("birch_trapdoor_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.JUNGLE_TRAPDOOR)).setRegistryName("jungle_trapdoor_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.ACACIA_TRAPDOOR)).setRegistryName("acacia_trapdoor_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DARK_OAK_TRAPDOOR)).setRegistryName("dark_oak_trapdoor_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CRACKED_STONE_BRICKS)).setRegistryName("cracked_stone_brick_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CHISELED_STONE_BRICKS)).setRegistryName("chiseled_stone_brick_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BROWN_MUSHROOM_BLOCK)).setRegistryName("brown_mushroom_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.RED_MUSHROOM_BLOCK)).setRegistryName("red_mushroom_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.MUSHROOM_STEM)).setRegistryName("mushroom_stem_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.IRON_BARS)).setRegistryName("iron_bars_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.MELON)).setRegistryName("melon_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.REPLACEABLE_PLANT).noCollission().strength(0.2F).sound(SoundType.GRASS)).setRegistryName("vine_slab"));
		event.getRegistry().register(new MyceliumSlab(AbstractBlock.Properties.copy(Blocks.MYCELIUM)).setRegistryName("mycelium_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.END_STONE)).setRegistryName("end_stone_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DRAGON_EGG)).setRegistryName("dragon_egg_slab"));
		event.getRegistry().register(new RedstoneLampSlab(AbstractBlock.Properties.copy(Blocks.REDSTONE_LAMP)).setRegistryName("redstone_lamp_slab"));
		event.getRegistry().register(new OreSlab(AbstractBlock.Properties.copy(Blocks.EMERALD_ORE)).setRegistryName("emerald_ore_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.EMERALD_BLOCK)).setRegistryName("emerald_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.REDSTONE_BLOCK)).setRegistryName("redstone_block_slab"));
		event.getRegistry().register(new OreSlab(AbstractBlock.Properties.copy(Blocks.NETHER_QUARTZ_ORE)).setRegistryName("nether_quartz_ore_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.HOPPER)).setRegistryName("hopper_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CHISELED_QUARTZ_BLOCK)).setRegistryName("chiseled_quartz_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.QUARTZ_PILLAR)).setRegistryName("quartz_pillar_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.WHITE_TERRACOTTA)).setRegistryName("white_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.ORANGE_TERRACOTTA)).setRegistryName("orange_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.MAGENTA_TERRACOTTA)).setRegistryName("magenta_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_BLUE_TERRACOTTA)).setRegistryName("light_blue_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.YELLOW_TERRACOTTA)).setRegistryName("yellow_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIME_TERRACOTTA)).setRegistryName("lime_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PINK_TERRACOTTA)).setRegistryName("pink_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GRAY_TERRACOTTA)).setRegistryName("gray_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_GRAY_TERRACOTTA)).setRegistryName("light_gray_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CYAN_TERRACOTTA)).setRegistryName("cyan_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PURPLE_TERRACOTTA)).setRegistryName("purple_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLUE_TERRACOTTA)).setRegistryName("blue_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BROWN_TERRACOTTA)).setRegistryName("brown_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GREEN_TERRACOTTA)).setRegistryName("green_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.RED_TERRACOTTA)).setRegistryName("red_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLACK_TERRACOTTA)).setRegistryName("black_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.SLIME_BLOCK)).setRegistryName("slime_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.IRON_TRAPDOOR)).setRegistryName("iron_trapdoor_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.SEA_LANTERN)).setRegistryName("sea_lantern_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.HAY_BLOCK)).setRegistryName("hay_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.TERRACOTTA)).setRegistryName("terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.COAL_BLOCK)).setRegistryName("coal_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PACKED_ICE)).setRegistryName("packed_ice_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CHISELED_RED_SANDSTONE)).setRegistryName("chiseled_red_sandstone_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PURPUR_PILLAR)).setRegistryName("purpur_pillar_slab"));
		event.getRegistry().register(new GrassPathSlab(AbstractBlock.Properties.copy(Blocks.GRASS_PATH)).setRegistryName("grass_path_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.of(Material.STONE, MaterialColor.NETHER).lightLevel((state) -> 3).strength(0.5F)).setRegistryName("magma_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.NETHER_WART_BLOCK)).setRegistryName("nether_wart_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BONE_BLOCK)).setRegistryName("bone_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.WHITE_GLAZED_TERRACOTTA)).setRegistryName("white_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.ORANGE_GLAZED_TERRACOTTA)).setRegistryName("orange_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.MAGENTA_GLAZED_TERRACOTTA)).setRegistryName("magenta_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA)).setRegistryName("light_blue_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.YELLOW_GLAZED_TERRACOTTA)).setRegistryName("yellow_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIME_GLAZED_TERRACOTTA)).setRegistryName("lime_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PINK_GLAZED_TERRACOTTA)).setRegistryName("pink_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GRAY_GLAZED_TERRACOTTA)).setRegistryName("gray_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA)).setRegistryName("light_gray_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CYAN_GLAZED_TERRACOTTA)).setRegistryName("cyan_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.PURPLE_GLAZED_TERRACOTTA)).setRegistryName("purple_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLUE_GLAZED_TERRACOTTA)).setRegistryName("blue_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BROWN_GLAZED_TERRACOTTA)).setRegistryName("brown_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GREEN_GLAZED_TERRACOTTA)).setRegistryName("green_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.RED_GLAZED_TERRACOTTA)).setRegistryName("red_glazed_terracotta_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLACK_GLAZED_TERRACOTTA)).setRegistryName("black_glazed_terracotta_slab"));
		event.getRegistry().register(white_concrete_slab);
		event.getRegistry().register(orange_concrete_slab);
		event.getRegistry().register(magenta_concrete_slab);
		event.getRegistry().register(light_blue_concrete_slab);
		event.getRegistry().register(yellow_concrete_slab);
		event.getRegistry().register(lime_concrete_slab);
		event.getRegistry().register(pink_concrete_slab);
		event.getRegistry().register(gray_concrete_slab);
		event.getRegistry().register(light_gray_concrete_slab);
		event.getRegistry().register(cyan_concrete_slab);
		event.getRegistry().register(purple_concrete_slab);
		event.getRegistry().register(blue_concrete_slab);
		event.getRegistry().register(brown_concrete_slab);
		event.getRegistry().register(green_concrete_slab);
		event.getRegistry().register(red_concrete_slab);
		event.getRegistry().register(black_concrete_slab);
		event.getRegistry().register(new ConcretePowderSlab(white_concrete_slab, AbstractBlock.Properties.copy(Blocks.WHITE_CONCRETE_POWDER)).setRegistryName("white_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(orange_concrete_slab, AbstractBlock.Properties.copy(Blocks.ORANGE_CONCRETE_POWDER)).setRegistryName("orange_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(magenta_concrete_slab, AbstractBlock.Properties.copy(Blocks.MAGENTA_CONCRETE_POWDER)).setRegistryName("magenta_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(light_blue_concrete_slab, AbstractBlock.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE_POWDER)).setRegistryName("light_blue_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(yellow_concrete_slab, AbstractBlock.Properties.copy(Blocks.YELLOW_CONCRETE_POWDER)).setRegistryName("yellow_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(lime_concrete_slab, AbstractBlock.Properties.copy(Blocks.LIME_CONCRETE_POWDER)).setRegistryName("lime_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(pink_concrete_slab, AbstractBlock.Properties.copy(Blocks.PINK_CONCRETE_POWDER)).setRegistryName("pink_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(gray_concrete_slab, AbstractBlock.Properties.copy(Blocks.GRAY_CONCRETE_POWDER)).setRegistryName("gray_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(light_gray_concrete_slab, AbstractBlock.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE_POWDER)).setRegistryName("light_gray_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(cyan_concrete_slab, AbstractBlock.Properties.copy(Blocks.CYAN_CONCRETE_POWDER)).setRegistryName("cyan_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(purple_concrete_slab, AbstractBlock.Properties.copy(Blocks.PURPLE_CONCRETE_POWDER)).setRegistryName("purple_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(blue_concrete_slab, AbstractBlock.Properties.copy(Blocks.BLUE_CONCRETE_POWDER)).setRegistryName("blue_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(brown_concrete_slab, AbstractBlock.Properties.copy(Blocks.BROWN_CONCRETE_POWDER)).setRegistryName("brown_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(green_concrete_slab, AbstractBlock.Properties.copy(Blocks.GREEN_CONCRETE_POWDER)).setRegistryName("green_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(red_concrete_slab, AbstractBlock.Properties.copy(Blocks.RED_CONCRETE_POWDER)).setRegistryName("red_concrete_powder_slab"));
		event.getRegistry().register(new ConcretePowderSlab(black_concrete_slab, AbstractBlock.Properties.copy(Blocks.BLACK_CONCRETE_POWDER)).setRegistryName("black_concrete_powder_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DRIED_KELP_BLOCK)).setRegistryName("dried_kelp_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DEAD_TUBE_CORAL_BLOCK)).setRegistryName("dead_tube_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DEAD_BRAIN_CORAL_BLOCK)).setRegistryName("dead_brain_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DEAD_BUBBLE_CORAL_BLOCK)).setRegistryName("dead_bubble_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DEAD_FIRE_CORAL_BLOCK)).setRegistryName("dead_fire_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.DEAD_HORN_CORAL_BLOCK)).setRegistryName("dead_horn_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.TUBE_CORAL_BLOCK)).setRegistryName("tube_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BRAIN_CORAL_BLOCK)).setRegistryName("brain_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BUBBLE_CORAL_BLOCK)).setRegistryName("bubble_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.FIRE_CORAL_BLOCK)).setRegistryName("fire_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.HORN_CORAL_BLOCK)).setRegistryName("horn_coral_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BLUE_ICE)).setRegistryName("blue_ice_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.HONEY_BLOCK)).setRegistryName("honey_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.HONEYCOMB_BLOCK)).setRegistryName("honeycomb_block_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.copy(Blocks.WARPED_STEM)).setRegistryName("warped_stem_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.STRIPPED_WARPED_STEM)).setRegistryName("stripped_warped_stem_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.copy(Blocks.WARPED_HYPHAE)).setRegistryName("warped_hyphae_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.STRIPPED_WARPED_HYPHAE)).setRegistryName("stripped_warped_hyphae_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.WARPED_NYLIUM)).setRegistryName("warped_nylium_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.WARPED_WART_BLOCK)).setRegistryName("warped_wart_block_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.copy(Blocks.CRIMSON_STEM)).setRegistryName("crimson_stem_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.STRIPPED_CRIMSON_STEM)).setRegistryName("stripped_crimson_stem_slab"));
		event.getRegistry().register(new LogSlab(AbstractBlock.Properties.copy(Blocks.CRIMSON_HYPHAE)).setRegistryName("crimson_hyphae_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.STRIPPED_CRIMSON_HYPHAE)).setRegistryName("stripped_crimson_hyphae_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CRIMSON_NYLIUM)).setRegistryName("crimson_nylium_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.SHROOMLIGHT)).setRegistryName("shroomlight_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.NETHERITE_BLOCK)).setRegistryName("netherite_block_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.ANCIENT_DEBRIS)).setRegistryName("ancient_debris_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CRYING_OBSIDIAN)).setRegistryName("crying_obsidian_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.BASALT)).setRegistryName("basalt_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.POLISHED_BASALT)).setRegistryName("polished_basalt_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS)).setRegistryName("cracked_polished_blackstone_brick_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CHISELED_POLISHED_BLACKSTONE)).setRegistryName("chiseled_polished_blackstone_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.GILDED_BLACKSTONE)).setRegistryName("gilded_blackstone_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CHISELED_NETHER_BRICKS)).setRegistryName("chiseled_nether_brick_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.CRACKED_NETHER_BRICKS)).setRegistryName("cracked_nether_brick_slab"));
		event.getRegistry().register(new SlabBlock(AbstractBlock.Properties.copy(Blocks.QUARTZ_BRICKS)).setRegistryName("quartz_brick_slab"));
	}

	@SubscribeEvent
	public static void registerSlabBlockItems(final RegistryEvent.Register<Item> event) {
		event.getRegistry().register(new BlockItem(farmland_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("farmland_slab"));
		event.getRegistry().register(new BlockItem(grass_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("grass_block_slab"));
		event.getRegistry().register(new BlockItem(dirt_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dirt_slab"));
		event.getRegistry().register(new BlockItem(coarse_dirt_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("coarse_dirt_slab"));
		event.getRegistry().register(new BlockItem(podzol_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("podzol_slab"));
		event.getRegistry().register(new BlockItem(bedrock_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("bedrock_slab"));
		event.getRegistry().register(new BlockItem(sand_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("sand_slab"));
		event.getRegistry().register(new BlockItem(red_sand_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("red_sand_slab"));
		event.getRegistry().register(new BlockItem(gravel_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gravel_slab"));
		event.getRegistry().register(new BlockItem(gold_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gold_ore_slab"));
		event.getRegistry().register(new BlockItem(iron_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("iron_ore_slab"));
		event.getRegistry().register(new BlockItem(coal_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("coal_ore_slab"));
		event.getRegistry().register(new BlockItem(nether_gold_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("nether_gold_ore_slab"));
		event.getRegistry().register(new BlockItem(oak_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("oak_log_slab"));
		event.getRegistry().register(new BlockItem(spruce_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("spruce_log_slab"));
		event.getRegistry().register(new BlockItem(birch_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("birch_log_slab"));
		event.getRegistry().register(new BlockItem(jungle_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("jungle_log_slab"));
		event.getRegistry().register(new BlockItem(acacia_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("acacia_log_slab"));
		event.getRegistry().register(new BlockItem(dark_oak_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dark_oak_log_slab"));
		event.getRegistry().register(new BlockItem(stripped_oak_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_oak_log_slab"));
		event.getRegistry().register(new BlockItem(stripped_spruce_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_spruce_log_slab"));
		event.getRegistry().register(new BlockItem(stripped_birch_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_birch_log_slab"));
		event.getRegistry().register(new BlockItem(stripped_jungle_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_jungle_log_slab"));
		event.getRegistry().register(new BlockItem(stripped_acacia_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_acacia_log_slab"));
		event.getRegistry().register(new BlockItem(stripped_dark_oak_log_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_dark_oak_log_slab"));
		event.getRegistry().register(new BlockItem(oak_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("oak_wood_slab"));
		event.getRegistry().register(new BlockItem(spruce_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("spruce_wood_slab"));
		event.getRegistry().register(new BlockItem(birch_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("birch_wood_slab"));
		event.getRegistry().register(new BlockItem(jungle_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("jungle_wood_slab"));
		event.getRegistry().register(new BlockItem(acacia_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("acacia_wood_slab"));
		event.getRegistry().register(new BlockItem(dark_oak_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dark_oak_wood_slab"));
		event.getRegistry().register(new BlockItem(stripped_oak_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_oak_wood_slab"));
		event.getRegistry().register(new BlockItem(stripped_spruce_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_spruce_wood_slab"));
		event.getRegistry().register(new BlockItem(stripped_birch_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_birch_wood_slab"));
		event.getRegistry().register(new BlockItem(stripped_jungle_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_jungle_wood_slab"));
		event.getRegistry().register(new BlockItem(stripped_acacia_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_acacia_wood_slab"));
		event.getRegistry().register(new BlockItem(stripped_dark_oak_wood_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_dark_oak_wood_slab"));
		event.getRegistry().register(new BlockItem(oak_leaves_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("oak_leaves_slab"));
		event.getRegistry().register(new BlockItem(spruce_leaves_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("spruce_leaves_slab"));
		event.getRegistry().register(new BlockItem(birch_leaves_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("birch_leaves_slab"));
		event.getRegistry().register(new BlockItem(jungle_leaves_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("jungle_leaves_slab"));
		event.getRegistry().register(new BlockItem(acacia_leaves_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("acacia_leaves_slab"));
		event.getRegistry().register(new BlockItem(dark_oak_leaves_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dark_oak_leaves_slab"));
		event.getRegistry().register(new BlockItem(sponge_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("sponge_slab"));
		event.getRegistry().register(new BlockItem(wet_sponge_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("wet_sponge_slab"));
		event.getRegistry().register(new BlockItem(glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("glass_slab"));
		event.getRegistry().register(new BlockItem(lapis_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("lapis_ore_slab"));
		event.getRegistry().register(new BlockItem(lapis_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("lapis_block_slab"));
		event.getRegistry().register(new BlockItem(chiseled_sandstone_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("chiseled_sandstone_slab"));
		event.getRegistry().register(new BlockItem(white_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("white_wool_slab"));
		event.getRegistry().register(new BlockItem(orange_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("orange_wool_slab"));
		event.getRegistry().register(new BlockItem(magenta_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("magenta_wool_slab"));
		event.getRegistry().register(new BlockItem(light_blue_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_blue_wool_slab"));
		event.getRegistry().register(new BlockItem(yellow_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("yellow_wool_slab"));
		event.getRegistry().register(new BlockItem(lime_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("lime_wool_slab"));
		event.getRegistry().register(new BlockItem(pink_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("pink_wool_slab"));
		event.getRegistry().register(new BlockItem(gray_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gray_wool_slab"));
		event.getRegistry().register(new BlockItem(light_gray_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_gray_wool_slab"));
		event.getRegistry().register(new BlockItem(cyan_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cyan_wool_slab"));
		event.getRegistry().register(new BlockItem(purple_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("purple_wool_slab"));
		event.getRegistry().register(new BlockItem(blue_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("blue_wool_slab"));
		event.getRegistry().register(new BlockItem(brown_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("brown_wool_slab"));
		event.getRegistry().register(new BlockItem(green_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("green_wool_slab"));
		event.getRegistry().register(new BlockItem(red_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("red_wool_slab"));
		event.getRegistry().register(new BlockItem(black_wool_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("black_wool_slab"));
		event.getRegistry().register(new BlockItem(gold_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gold_block_slab"));
		event.getRegistry().register(new BlockItem(iron_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("iron_block_slab"));
		event.getRegistry().register(new BlockItem(tnt_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("tnt_slab"));
		event.getRegistry().register(new BlockItem(bookshelf_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("bookshelf_slab"));
		event.getRegistry().register(new BlockItem(obsidian_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("obsidian_slab"));
		event.getRegistry().register(new BlockItem(spawner_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("spawner_slab"));
		event.getRegistry().register(new BlockItem(diamond_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("diamond_ore_slab"));
		event.getRegistry().register(new BlockItem(diamond_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("diamond_block_slab"));
		event.getRegistry().register(new BlockItem(redstone_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("redstone_ore_slab"));
		event.getRegistry().register(new BlockItem(ice_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("ice_slab"));
		event.getRegistry().register(new BlockItem(snow_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("snow_block_slab"));
		event.getRegistry().register(new BlockItem(clay_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("clay_slab"));
		event.getRegistry().register(new BlockItem(pumpkin_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("pumpkin_slab"));
		event.getRegistry().register(new BlockItem(netherrack_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("netherrack_slab"));
		event.getRegistry().register(new BlockItem(soul_sand_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("soul_sand_slab"));
		event.getRegistry().register(new BlockItem(soul_soil_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("soul_soil_slab"));
		event.getRegistry().register(new BlockItem(glowstone_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("glowstone_slab"));
		event.getRegistry().register(new BlockItem(carved_pumpkin_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("carved_pumpkin_slab"));
		event.getRegistry().register(new BlockItem(jack_o_lantern_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("jack_o_lantern_slab"));
		event.getRegistry().register(new BlockItem(white_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("white_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(orange_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("orange_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(magenta_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("magenta_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(light_blue_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_blue_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(yellow_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("yellow_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(lime_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("lime_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(pink_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("pink_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(gray_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gray_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(light_gray_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_gray_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(cyan_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cyan_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(purple_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("purple_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(blue_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("blue_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(brown_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("brown_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(green_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("green_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(red_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("red_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(black_stained_glass_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("black_stained_glass_slab"));
		event.getRegistry().register(new BlockItem(oak_trapdoor_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("oak_trapdoor_slab"));
		event.getRegistry().register(new BlockItem(spruce_trapdoor_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("spruce_trapdoor_slab"));
		event.getRegistry().register(new BlockItem(birch_trapdoor_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("birch_trapdoor_slab"));
		event.getRegistry().register(new BlockItem(jungle_trapdoor_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("jungle_trapdoor_slab"));
		event.getRegistry().register(new BlockItem(acacia_trapdoor_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("acacia_trapdoor_slab"));
		event.getRegistry().register(new BlockItem(dark_oak_trapdoor_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dark_oak_trapdoor_slab"));
		event.getRegistry().register(new BlockItem(cracked_stone_brick_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cracked_stone_brick_slab"));
		event.getRegistry().register(new BlockItem(chiseled_stone_brick_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("chiseled_stone_brick_slab"));
		event.getRegistry().register(new BlockItem(brown_mushroom_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("brown_mushroom_block_slab"));
		event.getRegistry().register(new BlockItem(red_mushroom_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("red_mushroom_block_slab"));
		event.getRegistry().register(new BlockItem(mushroom_stem_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("mushroom_stem_slab"));
		event.getRegistry().register(new BlockItem(iron_bars_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("iron_bars_slab"));
		event.getRegistry().register(new BlockItem(melon_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("melon_slab"));
		event.getRegistry().register(new BlockItem(vine_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("vine_slab"));
		event.getRegistry().register(new BlockItem(mycelium_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("mycelium_slab"));
		event.getRegistry().register(new BlockItem(end_stone_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("end_stone_slab"));
		event.getRegistry().register(new BlockItem(dragon_egg_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dragon_egg_slab"));
		event.getRegistry().register(new BlockItem(redstone_lamp_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("redstone_lamp_slab"));
		event.getRegistry().register(new BlockItem(emerald_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("emerald_ore_slab"));
		event.getRegistry().register(new BlockItem(emerald_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("emerald_block_slab"));
		event.getRegistry().register(new BlockItem(redstone_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("redstone_block_slab"));
		event.getRegistry().register(new BlockItem(nether_quartz_ore_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("nether_quartz_ore_slab"));
		event.getRegistry().register(new BlockItem(hopper_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("hopper_slab"));
		event.getRegistry().register(new BlockItem(chiseled_quartz_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("chiseled_quartz_block_slab"));
		event.getRegistry().register(new BlockItem(quartz_pillar_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("quartz_pillar_slab"));
		event.getRegistry().register(new BlockItem(white_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("white_terracotta_slab"));
		event.getRegistry().register(new BlockItem(orange_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("orange_terracotta_slab"));
		event.getRegistry().register(new BlockItem(magenta_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("magenta_terracotta_slab"));
		event.getRegistry().register(new BlockItem(light_blue_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_blue_terracotta_slab"));
		event.getRegistry().register(new BlockItem(yellow_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("yellow_terracotta_slab"));
		event.getRegistry().register(new BlockItem(lime_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("lime_terracotta_slab"));
		event.getRegistry().register(new BlockItem(pink_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("pink_terracotta_slab"));
		event.getRegistry().register(new BlockItem(gray_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gray_terracotta_slab"));
		event.getRegistry().register(new BlockItem(light_gray_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_gray_terracotta_slab"));
		event.getRegistry().register(new BlockItem(cyan_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cyan_terracotta_slab"));
		event.getRegistry().register(new BlockItem(purple_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("purple_terracotta_slab"));
		event.getRegistry().register(new BlockItem(blue_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("blue_terracotta_slab"));
		event.getRegistry().register(new BlockItem(brown_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("brown_terracotta_slab"));
		event.getRegistry().register(new BlockItem(green_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("green_terracotta_slab"));
		event.getRegistry().register(new BlockItem(red_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("red_terracotta_slab"));
		event.getRegistry().register(new BlockItem(black_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("black_terracotta_slab"));
		event.getRegistry().register(new BlockItem(slime_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("slime_block_slab"));
		event.getRegistry().register(new BlockItem(iron_trapdoor_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("iron_trapdoor_slab"));
		event.getRegistry().register(new BlockItem(sea_lantern_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("sea_lantern_slab"));
		event.getRegistry().register(new BlockItem(hay_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("hay_block_slab"));
		event.getRegistry().register(new BlockItem(terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("terracotta_slab"));
		event.getRegistry().register(new BlockItem(coal_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("coal_block_slab"));
		event.getRegistry().register(new BlockItem(packed_ice_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("packed_ice_slab"));
		event.getRegistry().register(new BlockItem(chiseled_red_sandstone_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("chiseled_red_sandstone_slab"));
		event.getRegistry().register(new BlockItem(purpur_pillar_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("purpur_pillar_slab"));
		event.getRegistry().register(new BlockItem(grass_path_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("grass_path_slab"));
		event.getRegistry().register(new BlockItem(magma_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("magma_block_slab"));
		event.getRegistry().register(new BlockItem(nether_wart_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("nether_wart_block_slab"));
		event.getRegistry().register(new BlockItem(bone_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("bone_block_slab"));
		event.getRegistry().register(new BlockItem(white_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("white_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(orange_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("orange_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(magenta_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("magenta_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(light_blue_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_blue_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(yellow_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("yellow_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(lime_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("lime_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(pink_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("pink_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(gray_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gray_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(light_gray_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_gray_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(cyan_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cyan_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(purple_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("purple_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(blue_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("blue_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(brown_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("brown_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(green_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("green_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(red_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("red_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(black_glazed_terracotta_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("black_glazed_terracotta_slab"));
		event.getRegistry().register(new BlockItem(white_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("white_concrete_slab"));
		event.getRegistry().register(new BlockItem(orange_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("orange_concrete_slab"));
		event.getRegistry().register(new BlockItem(magenta_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("magenta_concrete_slab"));
		event.getRegistry().register(new BlockItem(light_blue_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_blue_concrete_slab"));
		event.getRegistry().register(new BlockItem(yellow_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("yellow_concrete_slab"));
		event.getRegistry().register(new BlockItem(lime_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("lime_concrete_slab"));
		event.getRegistry().register(new BlockItem(pink_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("pink_concrete_slab"));
		event.getRegistry().register(new BlockItem(gray_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gray_concrete_slab"));
		event.getRegistry().register(new BlockItem(light_gray_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_gray_concrete_slab"));
		event.getRegistry().register(new BlockItem(cyan_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cyan_concrete_slab"));
		event.getRegistry().register(new BlockItem(purple_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("purple_concrete_slab"));
		event.getRegistry().register(new BlockItem(blue_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("blue_concrete_slab"));
		event.getRegistry().register(new BlockItem(brown_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("brown_concrete_slab"));
		event.getRegistry().register(new BlockItem(green_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("green_concrete_slab"));
		event.getRegistry().register(new BlockItem(red_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("red_concrete_slab"));
		event.getRegistry().register(new BlockItem(black_concrete_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("black_concrete_slab"));
		event.getRegistry().register(new BlockItem(white_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("white_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(orange_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("orange_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(magenta_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("magenta_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(light_blue_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_blue_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(yellow_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("yellow_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(lime_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("lime_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(pink_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("pink_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(gray_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gray_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(light_gray_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("light_gray_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(cyan_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cyan_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(purple_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("purple_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(blue_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("blue_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(brown_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("brown_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(green_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("green_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(red_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("red_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(black_concrete_powder_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("black_concrete_powder_slab"));
		event.getRegistry().register(new BlockItem(dried_kelp_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dried_kelp_block_slab"));
		event.getRegistry().register(new BlockItem(dead_tube_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dead_tube_coral_block_slab"));
		event.getRegistry().register(new BlockItem(dead_brain_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dead_brain_coral_block_slab"));
		event.getRegistry().register(new BlockItem(dead_bubble_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dead_bubble_coral_block_slab"));
		event.getRegistry().register(new BlockItem(dead_fire_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dead_fire_coral_block_slab"));
		event.getRegistry().register(new BlockItem(dead_horn_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("dead_horn_coral_block_slab"));
		event.getRegistry().register(new BlockItem(tube_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("tube_coral_block_slab"));
		event.getRegistry().register(new BlockItem(brain_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("brain_coral_block_slab"));
		event.getRegistry().register(new BlockItem(bubble_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("bubble_coral_block_slab"));
		event.getRegistry().register(new BlockItem(fire_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("fire_coral_block_slab"));
		event.getRegistry().register(new BlockItem(horn_coral_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("horn_coral_block_slab"));
		event.getRegistry().register(new BlockItem(blue_ice_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("blue_ice_slab"));
		event.getRegistry().register(new BlockItem(honey_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("honey_block_slab"));
		event.getRegistry().register(new BlockItem(honeycomb_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("honeycomb_block_slab"));
		event.getRegistry().register(new BlockItem(warped_stem_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("warped_stem_slab"));
		event.getRegistry().register(new BlockItem(stripped_warped_stem_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_warped_stem_slab"));
		event.getRegistry().register(new BlockItem(warped_hyphae_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("warped_hyphae_slab"));
		event.getRegistry().register(new BlockItem(stripped_warped_hyphae_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_warped_hyphae_slab"));
		event.getRegistry().register(new BlockItem(warped_nylium_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("warped_nylium_slab"));
		event.getRegistry().register(new BlockItem(warped_wart_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("warped_wart_block_slab"));
		event.getRegistry().register(new BlockItem(crimson_stem_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("crimson_stem_slab"));
		event.getRegistry().register(new BlockItem(stripped_crimson_stem_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_crimson_stem_slab"));
		event.getRegistry().register(new BlockItem(crimson_hyphae_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("crimson_hyphae_slab"));
		event.getRegistry().register(new BlockItem(stripped_crimson_hyphae_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("stripped_crimson_hyphae_slab"));
		event.getRegistry().register(new BlockItem(crimson_nylium_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("crimson_nylium_slab"));
		event.getRegistry().register(new BlockItem(shroomlight_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("shroomlight_slab"));
		event.getRegistry().register(new BlockItem(netherite_block_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("netherite_block_slab"));
		event.getRegistry().register(new BlockItem(ancient_debris_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("ancient_debris_slab"));
		event.getRegistry().register(new BlockItem(crying_obsidian_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("crying_obsidian_slab"));
		event.getRegistry().register(new BlockItem(basalt_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("basalt_slab"));
		event.getRegistry().register(new BlockItem(polished_basalt_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("polished_basalt_slab"));
		event.getRegistry().register(new BlockItem(cracked_polished_blackstone_brick_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cracked_polished_blackstone_brick_slab"));
		event.getRegistry().register(new BlockItem(chiseled_polished_blackstone_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("chiseled_polished_blackstone_slab"));
		event.getRegistry().register(new BlockItem(gilded_blackstone_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("gilded_blackstone_slab"));
		event.getRegistry().register(new BlockItem(chiseled_nether_brick_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("chiseled_nether_brick_slab"));
		event.getRegistry().register(new BlockItem(cracked_nether_brick_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("cracked_nether_brick_slab"));
		event.getRegistry().register(new BlockItem(quartz_brick_slab, new Item.Properties().tab(VanillaExtension.VanillaExtensionItemGroup.instance)).setRegistryName("quartz_brick_slab"));
	}

}
